
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Menlo"
style = "Heavy"

[font.bold_italic]
family = "Menlo"
style = "Heavy Italic"

[font.italic]
family = "Menlo"
style = "Regular Italic"

[font.normal]
family = "Menlo"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0000\""
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000%"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
lfcd
"""
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000[/"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0000g"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000G"
key = "G"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0000o"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GoToCommand
"""
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000T"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GoToFile
"""
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GoToCommand
"""
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
:q
"""
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000P"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0000x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000F"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\t"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0000:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00001"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00002"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00003"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00004"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00005"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00006"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00007"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00008"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00009"
key = "Key9"
mods = "Command"

[window]
#decorations = "buttonless"
dynamic_padding = false
#opacity = 0.9

[window.padding]
x = 14
y = 10

[colors.primary]
foreground = "#ffffe0"
background = "#282828"

[general]
live_config_reload = true
